---
- name: play to create a file and directory
  hosts: webserver
  become: true
  remote_user: ec2-user
  tasks: 
    - name: create a folder
      file: 
       path: /opt/dir1
       state: directory
       owner: root
       group: root
       mode: 0755
    - name: download the content 
      get_url:
          url: https://docs.ansible.com/ansible/2.3/get_url_module.html
          dest: /opt/dir1/
         
