---
- name: remove httpd
  hosts: webservers
  become: true
  remote_user: ec2-user
  tasks:
    - name: remove httpd 
      yum:
        name: 'http*'
        state: absent 
    - name: remove vsftpd
      yum: 
        name: vsftpd
        state: absent
