---
- name: install nginx
  hosts: webservers
  become: true
  remote_user: ec2-user
  tasks: 
    - name: install the nginx rpm from a remote repo
      get_url:
          url: http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.11.0-1.el7.ngx.x86_64.rpm
          dest: /tmp/
          mode: 0644
    - name: install nginx rpm from a local file
      yum:
       name: /tmp/nginx-1.11.0-1.el7.ngx.x86_64.rpm
    - name: service start nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
       
