---
- name: play to create http auth
  hosts: webserver
  become: true
  remote_user: centos
  tasks:
    - name: create a floder
      file:
        path: /var/www/html/private
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: replace httpd.conf contents
      replace:
        dest: /etc/httpd/conf/httpd.conf
        regexp: 'AllowOverride None'
        replace: 'AllowOverride AuthConfig'

    - name:  create index html
      copy:
        dest: /var/www/html/private/index.html
        content: "This node {{ ansible_hostname }} is protected"

    - name: restart the service
      service:
        name: httpd
        state: restarted
        enabled: yes
