---
- name: play to shutdown
  hosts: webserver
  become: true
  remote_user: ec2-user
  tasks: 
    - name: stop the servera
      service: 
       name: httpd
       state: stopped
      when: ansible_nodename == 'ip-172-31-16-97.ap-south-1.compute.internal'
      
