---
- name: play to use tags
  hosts: all
  become: true
  remote_user: ec2-user
  tasks:
    - name: tar the httpd filed
      command: tar -cvf /var/tmp/webserver.tar.gz /var/www/html
      tags: webserver
      when: inventory_hostname in groups ['webserver']
    - name: tar httpd logs
      command: tar cvf /var/tmp/backup.tar.gz /var/log/httpd
      tags: backup
      when: inventory_hostname in groups ['backup']
      
